config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :comments
  resources :incidents
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/incident.rb
class Incident < ApplicationRecord
  belongs_to :user_normal
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: %i[ show edit update destroy ]

  # GET /incidents or /incidents.json
  def index
    @incidents = Incident.all
  end

  # GET /incidents/1 or /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents or /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to incident_url(@incident), notice: "Incident was successfully created." }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1 or /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to incident_url(@incident), notice: "Incident was successfully updated." }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1 or /incidents/1.json
  def destroy
    @incident.destroy

    respond_to do |format|
      format.html { redirect_to incidents_url, notice: "Incident was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def incident_params
      params.require(:incident).permit(:incident_date, :description, :summary, :user_normal_id)
    end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<%= form_with(model: incident) do |form| %>
  <% if incident.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
        <% incident.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :incident_date, style: "display: block" %>
    <%= form.date_field :incident_date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_field :summary %>
  </div>

  <div>
    <%= form.label :user_normal_id, style: "display: block" %>
    <%= form.text_field :user_normal_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/incidents/_incident.html.erb
<div id="<%= dom_id incident %>">
  <p>
    <strong>Incident date:</strong>
    <%= incident.incident_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= incident.description %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= incident.summary %>
  </p>

  <p>
    <strong>User normal:</strong>
    <%= incident.user_normal_id %>
  </p>

</div>

app/views/incidents/edit.html.erb
<h1>Editing incident</h1>

<%= render "form", incident: @incident %>

<br>

<div>
  <%= link_to "Show this incident", @incident %> |
  <%= link_to "Back to incidents", incidents_path %>
</div>

app/views/incidents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Incidents</h1>

<div id="incidents">
  <% @incidents.each do |incident| %>
    <%= render incident %>
    <p>
      <%= link_to "Show this incident", incident %>
    </p>
  <% end %>
</div>

<%= link_to "New incident", new_incident_path %>

app/views/incidents/new.html.erb
<h1>New incident</h1>

<%= render "form", incident: @incident %>

<br>

<div>
  <%= link_to "Back to incidents", incidents_path %>
</div>

app/views/incidents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @incident %>

<div>
  <%= link_to "Edit this incident", edit_incident_path(@incident) %> |
  <%= link_to "Back to incidents", incidents_path %>

  <%= button_to "Destroy this incident", @incident, method: :delete %>
</div>