config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :comments
  resources :incidents
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :incident
  belongs_to :user_normal
  belongs_to :user_administrator
  belongs_to :user_supervisor
  belongs_to :user_executive

  enum status: { normal: 0, ejecutivo: 1, supervisor: 2, administrador: 3 }

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:claim_date, :due_date, :priority, :status, :incident_id, :user_normal_id, :user_administrator_id, :user_supervisor_id, :user_executive_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :claim_date, style: "display: block" %>
    <%= form.date_field :claim_date %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :priority, style: "display: block" %>
    <%= form.number_field :priority %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :incident_id, style: "display: block" %>
    <%= form.text_field :incident_id %>
  </div>

  <div>
    <%= form.label :user_normal_id, style: "display: block" %>
    <%= form.text_field :user_normal_id %>
  </div>

  <div>
    <%= form.label :user_administrator_id, style: "display: block" %>
    <%= form.text_field :user_administrator_id %>
  </div>

  <div>
    <%= form.label :user_supervisor_id, style: "display: block" %>
    <%= form.text_field :user_supervisor_id %>
  </div>

  <div>
    <%= form.label :user_executive_id, style: "display: block" %>
    <%= form.text_field :user_executive_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <p>
    <strong>Claim date:</strong>
    <%= ticket.claim_date %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= ticket.due_date %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= ticket.priority %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= ticket.status %>
  </p>

  <p>
    <strong>Incident:</strong>
    <%= ticket.incident_id %>
  </p>

  <p>
    <strong>User normal:</strong>
    <%= ticket.user_normal_id %>
  </p>

  <p>
    <strong>User administrator:</strong>
    <%= ticket.user_administrator_id %>
  </p>

  <p>
    <strong>User supervisor:</strong>
    <%= ticket.user_supervisor_id %>
  </p>

  <p>
    <strong>User executive:</strong>
    <%= ticket.user_executive_id %>
  </p>

</div>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
    <p>
      <%= link_to "Show this ticket", ticket %>
    </p>
  <% end %>
</div>

<%= link_to "New ticket", new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div>
  <%= link_to "Edit this ticket", edit_ticket_path(@ticket) %> |
  <%= link_to "Back to tickets", tickets_path %>

  <%= button_to "Destroy this ticket", @ticket, method: :delete %>
</div>